<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="15333" started-at="2018-10-16T14:38:30Z" finished-at="2018-10-16T14:38:45Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="15333" started-at="2018-10-16T14:38:30Z" finished-at="2018-10-16T14:38:45Z">
      <class name="pe.com.test.system.testCase.MantenimientoCategoria">
        <test-method status="PASS" signature="antesDelTest(java.lang.String, int)[pri:0, instance:pe.com.test.system.testCase.MantenimientoCategoria@59f99ea]" name="antesDelTest" is-config="true" duration-ms="2995" started-at="2018-10-16T14:38:30Z" finished-at="2018-10-16T14:38:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- antesDelTest -->
        <test-method status="FAIL" signature="insertarCategoria_Criterio01()[pri:0, instance:pe.com.test.system.testCase.MantenimientoCategoria@59f99ea]" name="insertarCategoria_Criterio01" duration-ms="11591" started-at="2018-10-16T14:38:33Z" finished-at="2018-10-16T14:38:45Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at pe.com.test.system.testCase.MantenimientoCategoria.insertarCategoria_Criterio01(MantenimientoCategoria.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- insertarCategoria_Criterio01 -->
        <test-method status="SKIP" signature="insertarCategoria_Criterio02()[pri:0, instance:pe.com.test.system.testCase.MantenimientoCategoria@59f99ea]" name="insertarCategoria_Criterio02" duration-ms="0" started-at="2018-10-16T14:38:45Z" depends-on-methods="pe.com.test.system.testCase.MantenimientoCategoria.insertarCategoria_Criterio01" finished-at="2018-10-16T14:38:45Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MantenimientoCategoria.insertarCategoria_Criterio02()[pri:0, instance:pe.com.test.system.testCase.MantenimientoCategoria@59f99ea] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MantenimientoCategoria.insertarCategoria_Criterio02()[pri:0, instance:pe.com.test.system.testCase.MantenimientoCategoria@59f99ea] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- insertarCategoria_Criterio02 -->
        <test-method status="PASS" signature="despuesDelTest()[pri:0, instance:pe.com.test.system.testCase.MantenimientoCategoria@59f99ea]" name="despuesDelTest" is-config="true" duration-ms="716" started-at="2018-10-16T14:38:45Z" finished-at="2018-10-16T14:38:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- despuesDelTest -->
      </class> <!-- pe.com.test.system.testCase.MantenimientoCategoria -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
